require_relative 'code_objects/headers_root'
require_relative 'code_objects/header_base_object'
require_relative 'code_objects/header_object'
require_relative 'code_objects/function_object'
require_relative 'code_objects/define_object'
require_relative 'code_objects/typedef_object'
